language: php

php:
    - 5.4

before_script:
    - composer self-update
    - composer install --dev --prefer-dist

script:
    - php vendor/bin/phpunit
    - php vendor/bin/behat

notifications:
    email: true
